language: node_js
node_js:
    - '10'
cache: yarn
script:
    - NODE_ENV=production yarn build
deploy:
    on:
        branch: develop
    provider: firebase
    token:
        secure: d3Ebi0OMmLpd6lSBPf/irhqtda1dqCRlBe6lfIWuO2XxEKsgrA30bel8DF5Ga2cAS2dmUMb/Wy9LAn2RPb2k2GrCByyvMQNwVzJqoMIplnIIGhf/qiTPwk/izAClpAMLdsw+WPHcK0puuqmON+woC+zRUZQoCIeodg7lo0cKi6kn4JoIZZw6k43VszgIiQxweFjn8NIAEZ8nEcG03CnnznEizawElph3eOmcXOO/I2D4Lazlsg8CyCBvJdG0SWgVnnb3zGYhZK1SD5rKuTAHM42ngHJS0jXa5ryJqh0flgrqH9MKG021+1jF4HgIgLV0iF8gzJGiRA1bj2HA3c4K9/o+qBZCiVvBQ6W2Hz7O9K6zxmU/HBI1uAn3X9lYl2I4iRzR0CooUU8cvZeqQ8HZuPAOrqQ9dF00qV/vWWJH5RB0iZYwDhfvJ1B1Yt9wZ/CFXPUyWuhZiHVu36M4ZYU9ymAvyuYwoYCT5nGTnmWfNJUP+MI52FGmZdbHFK4UzFzlaQMJcDwGxkzb6liS6Z3n5DDOrquugI72u3oWGSEvWmwsSpjUHv8Ac1XoPBCpNSDfexDEz/yRjDfOZ5umh/I5JcXHcm33SUWyHRl6tlqbTRbZKGTpT+vCbkk1XXtJx4i8EaD6Wc6q6UIvXvlgMjXyVFDhSL3Ax9LUOrIfmtEqhRw=
