language: node_js
node_js:
- '10'
cache: yarn
script:
- NODE_ENV=production yarn build
deploy:
  on:
    branch: develop
  provider: firebase
  token:
    secure: cjZqFISajO0pj+lHXd46k/wb7F0qnWqfG+6+BdoRzLqbwQVo2uFXBXf64tTt9NU4U6UhgxmOmySBkGV+JIKmrGUvX8Ti6yWjwlS9PtA2mqNo8efol+8PvqfFcsDD4gH3onAbj2NXIv2Gjcazs0IoTM40SyCTrHm+hvMe0ntjqk/ac55K3Vw6dwDJy3au9Y96ixPkTWh5oT55oH6Nmvcxj49yzpppw+bUoGuZ+gi3v8PQqxXtrKD91VkQRgnUDtD/mPIHnawMuM0rTEeA7e9n9I65RGoPTA90ntxphgimd0uDHRi77iAjduGkj7z6hoJuffEU4ABZ88znq+2L2pwkbDqokjqEFiEdH56N33JpFEEPd4afnw6jS3KQaJCEk9iaCoWIdy7UfIFkApyvYewpGwvR2Goi+S3iF2omNuE77p94IrCSyLoJ+9XnxeqMe89S7Rgr43ay3C606oCNo+LPtvXjzPvqGYPRUOGt+NgyFXZ8hVUyYTBpSXpbn76x3ikI7kFRP0WSqNPDpo40xChzscf5A/j/1SpByjCETbmSfdH9m0bOE/aXxHfi5xhFRvQgXzuKpZNSrJXC6YdymMFO1HWgPQRpj9iI5C4hkMaD4sReMBUoaWxDu0h1eBoPKbzG8dKLmOAEvtHNrSTCC4yKlw9AttZL6V0MSFFHskCskBw=
  message: "Deploy $TRAVIS_COMMIT "
