version: "3.3"

services:
  dev:
    container_name: when-the-last
    build:
      context: ./docker
      args:
        - YOUR_APP_WEB_HTTP_PORT=8080
    ports:
      - "8080:8080"
      - "8002:8000"  # only needed if using vue-cli UI
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    environment:
      # https://cli.vuejs.org/guide/mode-and-env.html#modes
      # development is used by vue-cli-service serve
      - NODE_ENV=development
      # one way for hot reloading ... see above for details
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - YOUR_APP_WEB_HTTP_PORT=8080
